global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp:25'
  smtp_from: 'alertmanager@example.org'

route:
  receiver: "email"
  group_by: ['alertname']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 5m

receivers:
- name: "email"
  email_configs:
  - to: gautambhatrcb@gmail.com
    from: gautambhatka@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: gautambhatka@gmail.com
    auth_identity: gautambhatka@gmail.com
    # enter your gmail app password here and change email address accordingly
    auth_password: #password
    html: '{{ template "email" .}}'
    send_resolved: true
templates:
  - '/etc/prometheus/email-template.tmpl'