version: '3.2'

services:
  mysql:
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.sql:/data/application/init.sql
    environment:
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'billie'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
    healthcheck:
      test: [ "CMD", "mysql -u root  -e 'use billie; select 1 from invoices_data limit 1' " ]
      interval: 10s
      timeout: 5s
      retries: 3
  sqlagent:
    image: dbhi/sql-agent
    ports:
      - 5000
  prometheus-sql:
    image: dbhi/prometheus-sql
    command: -service http://sqlagent:5000 -config prometheus-sql.yml
    ports:
      - 8080
    volumes:
      - ./prometheus-sql/prometheus-sql.yml:/prometheus-sql.yml
      - ./prometheus-sql/queries.yml:/queries.yml
    depends_on: 
      - mysql
  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/simple.rules:/etc/prometheus/simple.rules
    depends_on: 
      - prometheus-sql
  grafana:
    image: grafana/grafana
    ports: 
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    depends_on: 
      - prometheus
  alertmanager:
    image: prom/alertmanager
    command: --config.file=/prometheus/alertmanager.yml
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/prometheus/alertmanager.yml
      - ./alertmanager/email-template.tmpl:/etc/prometheus/email-template.tmpl


    
